from database import SessionLocal, engine
import models
from models import Base, Categoria

Base.metadata.create_all(bind=engine)

LISTA_CIDADES_SE = [
    "Amparo de São Francisco", "Aquidabã", "Aracaju", "Arauá", "Areia Branca", "Barra dos Coqueiros", 
    "Boquim", "Brejo Grande", "Campo do Brito", "Canhoba", "Canindé de São Francisco", "Capela", 
    "Carira", "Carmópolis", "Cedro de São João", "Cristinápolis", "Cumbe", "Divina Pastora", 
    "Estância", "Feira Nova", "Frei Paulo", "Gararu", "General Maynard", "Gracho Cardoso", 
    "Ilha das Flores", "Indiaroba", "Itabaiana", "Itabaianinha", "Itaporanga d'Ajuda", "Japaratuba", 
    "Japoatã", "Lagarto", "Laranjeiras", "Macambira", "Malhada dos Bois", "Malhador", 
    "Maruim", "Moita Bonita", "Monte Alegre de Sergipe", "Muribeca", "Neópolis", "Nossa Senhora da Glória", 
    "Nossa Senhora das Dores", "Nossa Senhora de Lourdes", "Nossa Senhora do Socorro", "Pacatuba", 
    "Pedra Mole", "Pedrinhas", "Pinhão", "Pirambu", "Poço Redondo", "Poço Verde", "Porto da Folha", 
    "Propriá", "Riachão do Dantas", "Riachuelo", "Ribeirópolis", "Rosário do Catete", "Salgado", 
    "Santa Luzia do Itanhy", "Santa Rosa de Lima", "Santana do São Francisco", "Santo Amaro das Brotas", 
    "São Cristóvão", "São Domingos", "São Francisco", "São Miguel do Aleixo", "Simão Dias", 
    "Siriri", "Telha", "Tobias Barreto", "Tomar do Geru", "Umbaúba"
]

# Exemplo de expansão para as 1000 categorias (Adicione as suas aqui)
CATEGORIAS_MASTER = [
   "Abatedor", "Aboio", "Açaitista", "Açougueiro", "Aderecista", "Adestrador", 
    "Administrador", "Advogado Cível", "Advogado Criminalista", "Advogado de Família", 
    "Advogado Previdenciário", "Advogado Trabalhista", "Advogado Tributarista", 
    "Aferidor", "Afiador", "Agente Comunitário", "Agente de Aeroporto", 
    "Agente de Saúde", "Agente de Turismo", "Agente de Viagens", "Agente Funerário", 
    "Agente Portuário", "Agricultor", "Agrônomo", "Ajudante de Carga", "Alambiqueiro", 
    "Alfaiate", "Algodoeiro", "Alinhador", "Almoxarife", "Alpinista Industrial", 
    "Amolador de Facas", "Analista de Dados", "Analista de Mídias Sociais", 
    "Analista de RH", "Analista de Sistemas", "Analista de Suporte", "Animador de Festas", 
    "Antropólogo", "Apicultor", "Apontador de Obras", "Arqueólogo", "Arquiteto", 
    "Armador de Ferragens", "Arrematador", "Arrumadeira", "Artesão de Barro", 
    "Artesão de Coco", "Artesão de Couro", "Artesão de Palha", "Artesão de Pneu", 
    "Artesão de Renda", "Articulador Cultural", "Asfaltador", "Assentador de Piso", 
    "Assistência Celular", "Assistente Social", "Atendente de Farmácia", "Ator", 
    "Auditor", "Auxiliar de Cozinha", "Auxiliar de Dentista", "Auxiliar de Escritório", 
    "Auxiliar de Limpeza", "Auxiliar de Mecânico", "Avaliador de Imóveis", "Azulejista", 
    "Babá", "Babá de Pets", "Baiana de Acarajé", "Bailarino", "Balanceador", 
    "Balconista", "Banhista de Pets", "Barbeiro", "Barman", "Barqueiro", 
    "Batedor de Açaí", "Bibliotecário", "Biólogo", "Biomédico", "Boleira", 
    "Bonequeiro", "Borracheiro", "Bordadeira", "Botânico", "Brigadista", "Buffet", 
    "Cabeleireiro", "Caçambeiro", "Caça-vazamentos", "Caixa", "Caldeireiro", 
    "Calheiro", "Caminhão Pipa", "Canteiro", "Capataz", "Capineiro", "Capoeirista", 
    "Capoteiro", "Carpinteiro", "Carreteiro", "Carroceiro", "Caseiro", "Castanheiro", 
    "Catador de Caranguejo", "Catador de Recicláveis", "Cenógrafo", "Ceramista", 
    "Cerimonialista", "Chapeiro", "Chaveiro", "Churrasqueiro", "Cinegrafista", 
    "Clínico Geral", "Coach", "Cobrador", "Coletor de Lixo", "Colhedor", "Colorista", 
    "Comissário de Bordo", "Compositor", "Confeiteiro", "Conferente", 
    "Consultor de Vendas", "Contador", "Controlador de Acesso", "Copeiro", 
    "Cordelista", "Corretor de Imóveis", "Corretor de Seguros", "Cortador de Cana", 
    "Costureira", "Couveiro", "Cozinheiro de Engenho", "Cozinheiro Industrial", 
    "Cozinheiro Particular", "Cuidador de Idosos", "Cuidador de Pets", "Cunhador", 
    "Curador de Arte", "Curandeiro", "Dançarino de Forró", "Dançarino de Frevo", 
    "Decorador", "Dedetizador", "Degustador de Café", "Delegado", "Demolidor", 
    "Dentista", "Depiladora", "Dermatologista", "Desenhista", "Designer de Interiores", 
    "Designer de Joias", "Designer de Sobrancelhas", "Designer Gráfico", "Designer UX", 
    "Desossador", "Despachante", "Detetive Particular", "Diarista", "Digitador", 
    "Diretor de Arte", "Docente", "Doceira", "Domador de Cavalos", "Dublador", 
    "Ecólogo", "Economista", "Editor de Vídeo", "Educador Físico", "Educador Social", 
    "Eletricista de Autos", "Eletricista de Redes", "Eletricista Predial", 
    "Eletromecânico", "Embalador", "Empregada Doméstica", "Encanador", "Encadernador", 
    "Enfermeiro", "Engajador", "Engenheiro Agrônomo", "Engenheiro Ambiental", 
    "Engenheiro Civil", "Engenheiro da Computação", "Engenheiro de Alimentos", 
    "Engenheiro de Pesca", "Engenheiro de Petróleo", "Engenheiro de Produção", 
    "Engenheiro de Segurança", "Engenheiro de Software", "Engenheiro Elétrico", 
    "Engenheiro Mecânico", "Engraxate", "Entregador", "Escritor", "Escriturário", 
    "Escultor de Carrancas", "Escultor de Madeira", "Esmaltadora", 
    "Especialista em Marketing", "Especialista em SEO", "Estampador", "Estatístico", 
    "Esteticista", "Estivador", "Estofador", "Estoquista", "Extrativista", 
    "Fabricante de Redes", "Fabricante de Selas", "Farmacêutico", "Farinheiro", 
    "Faxineiro", "Feirante", "Ferreiro", "Ferroviário", "Figurante", "Figurinista", 
    "Filósofo", "Fisioterapeuta", "Florista", "Fonoaudiólogo", "Forneiro", 
    "Fotógrafo de Casamento", "Fotógrafo de Eventos", "Freteiro", "Fruticultor", 
    "Funileiro", "Gaitista", "Gari", "Garçom", "Garimpeiro", "Gesseiro", 
    "Gestor Ambiental", "Gestor Financeiro", "Gestor de Tráfego", "Gestor Hospitalar", 
    "Ginasta", "Grafiteiro", "Graniteiro", "Graxista", "Guarda Municipal", 
    "Guarda-Vidas", "Guia de Turismo", "Guinchista", "Guincho", "Guitarrista", 
    "Hacker Ético", "Harpista", "Hematologista", "Herborista", "Hidráulico", 
    "Higienista Bucal", "Hipnoterapeuta", "Historiador", "Homeopata", "Horticultor", 
    "Hostess", "Humorista", "Ialorixá", "Ictiólogo", "Iluminador", "Ilustrador", 
    "Imobilizador Ortopédico", "Implantodontista", "Importador", "Impressor Digital", 
    "Infectologista", "Influenciador Digital", "Inseminador Artificial", 
    "Inspetor de Alunos", "Inspetor de Qualidade", "Instalador de Alarme", 
    "Instalador de Antenas", "Instalador de Ar-condicionado", "Instalador de Drywall", 
    "Instalador de Gás", "Instalador de Painel Solar", "Instalador de Redes", 
    "Instalador de Som", "Instrutor de Academia", "Instrutor de Autoescola", 
    "Instrutor de Drone", "Instrutor de Ioga", "Instrutor de Surf", 
    "Instrumentador Cirúrgico", "Intérprete de Libras", "Investigador Particular", 
    "Investidor", "Irrigador", "Isolador Térmico", "Jangadeiro", "Jardineiro Paisagista", 
    "Jatista de Areia", "Joalheiro", "Jóquei", "Jornaleiro", "Jornalista", 
    "Juiz de Direito", "Juiz de Futebol", "Juremeiro", "Jurista", "Kaitista", 
    "Kardexista", "Kinesiologista", "Kitesurfista", "Lactarista", "Ladrilheiro", 
    "Lagosteiro", "Lancheiro", "Lanterneiro", "Lapidador", "Lavadeira", 
    "Lavador de Carros", "Lavador de Fachadas", "Lavador de Tapetes", "Lavrador", 
    "Leiloeiro", "Leiteiro", "Letrista", "Linhoneiro", "Lixeiro", "Locutor", 
    "Lojista", "Lubrificador", "Lustrador de Móveis", "Luthier de Rabeca", 
    "Luthier de Sanfona", "Mãe de Santo", "Maestro", "Magarefe", "Mágico", 
    "Maître", "Malabarista", "Manicure", "Manobrista", "Manutentor Predial", 
    "Maquiadora", "Maquinista", "Marceneiro", "Marcador de Gado", "Marchante", 
    "Marinheiro", "Marisqueira", "Marmorista", "Marreteiro", "Massoterapeuta", 
    "Matemático", "Mecânico de Aeronaves", "Mecânico de Bicicletas", 
    "Mecânico de Caminhão", "Mecânico de Máquina de Costura", "Mecânico de Motos", 
    "Mecânico de Refrigeração", "Mecânico Industrial", "Mecatronista", 
    "Médico Veterinário", "Mergulhador", "Mestre de Obras", "Mestre de Reisado", 
    "Mestre Salineiro", "Metalúrgico", "Meteorologista", "Microbiologista", 
    "Micropigmentadora", "Militar", "Minerador", "Modelista", "Modelo", 
    "Modista", "Moedor de Cana", "Monitor de Recreação", "Montador de Andaimes", 
    "Montador de Estruturas", "Montador de Móveis", "Mordomo", "Motoboy", 
    "Motorista de Ambulância", "Motorista de Aplicativo", "Motorista de Caminhão Pipa", 
    "Motorista de Ônibus", "Motorista Particular", "Mototaxista", "Museólogo", 
    "Musicista", "Musicoterapeuta", "Navegador", "Nefrologista", "Neuropsicólogo", 
    "Nutricionista", "Obstetra", "Oculista", "Odontologista", "Office Boy", 
    "Oleiro", "Operador de Caixa", "Operador de Empilhadeira", 
    "Operador de Máquinas Agrícolas", "Operador de Roçadeira", 
    "Operador de Telemarketing", "Organizador de Eventos", "Ortodontista", 
    "Ourives", "Padeiro", "Pajé", "Paleontólogo", "Palhaço", "Panfleteiro", 
    "Pecuarista", "Pedagogo", "Pedicure", "Pedreiro", "Peão de Boiadeiro", 
    "Peixeiro", "Perfumista", "Perito Criminal", "Pescador", "Pescador de Curral", 
    "Personal Trainer", "Pintor Automotivo", "Pintor de Paredes", "Pizzaiolo", 
    "Podólogo", "Porteiro", "Prensador", "Professor de Artes", "Professor de Dança", 
    "Professor de Idiomas", "Professor de Música", "Programador", "Promotor de Vendas", 
    "Psicólogo", "Psiquiatra", "Publicitário", "Queijeiro", "Radialista", 
    "Radiologista", "Rasteleiro", "Rebarbador", "Recepcionista", "Redator", 
    "Regente", "Relojoeiro", "Rendeira de Bilro", "Reparador de Eletrodomésticos", 
    "Repórter", "Repositor", "Representante Comercial", "Restaurador", 
    "Roteirista", "Santeiro", "Sapateiro", "Secretária", "Segurança", "Seringueiro", 
    "Serrador", "Serralheiro", "Sertanejo", "Sushiman", "Soldador", "Sonoplasta", 
    "Tanoeiro", "Tapeceiro", "Tatuador", "Técnico Agrícola", "Técnico de Enfermagem", 
    "Técnico de Informática", "Técnico de Refrigeração", "Técnico em Agrimensura", 
    "Técnico em Edificações", "Técnico em Eletrônica", "Técnico em Energias Renováveis", 
    "Técnico em Estética", "Técnico em Logística", "Técnico em Meio Ambiente", 
    "Técnico em Radiologia", "Técnico em Segurança do Trabalho", "Telhadista", 
    "Terapeuta Ocupacional", "Topógrafo", "Tosador", "Tradutor", "Tratorista", 
    "Turismólogo", "Urologista", "Vaqueiro", "Vaqueiro de Gibão", "Velejador", 
    "Vendedor", "Vendedor Ambulante", "Vendedor de Picolé", "Veterinário", 
    "Vidraceiro", "Vigilante", "Vitrinista", "Xilógrafo", "Zelador", "Zootecnista", "Outros"]

def popular_sistema():
    db = SessionLocal()
    print("🚀 Sincronizando Sergipe e Categorias... 🌵")
    lista_final = sorted(list(set(CATEGORIAS_MASTER)))
    if "Outros" in lista_final: lista_final.remove("Outros")
    lista_final.append("Outros")

    for nome in lista_final:
        if not db.query(Categoria).filter_by(nome=nome).first():
            db.add(Categoria(nome=nome))
    db.commit()
    db.close()
    print("✅ Banco pronto!")

if __name__ == "__main__":
    popular_sistema()