from database import SessionLocal, engine
import models
from models import Base, Categoria

Base.metadata.create_all(bind=engine)

LISTA_CIDADES_SE = [
    "Amparo de São Francisco", "Aquidabã", "Aracaju", "Arauá", "Areia Branca", "Barra dos Coqueiros", 
    "Boquim", "Brejo Grande", "Campo do Brito", "Canhoba", "Canindé de São Francisco", "Capela", 
    "Carira", "Carmópolis", "Cedro de São João", "Cristinápolis", "Cumbe", "Divina Pastora", 
    "Estância", "Feira Nova", "Frei Paulo", "Gararu", "General Maynard", "Gracho Cardoso", 
    "Ilha das Flores", "Indiaroba", "Itabaiana", "Itabaianinha", "Itaporanga d'Ajuda", "Japaratuba", 
    "Japoatã", "Lagarto", "Laranjeiras", "Macambira", "Malhada dos Bois", "Malhador", 
    "Maruim", "Moita Bonita", "Monte Alegre de Sergipe", "Muribeca", "Neópolis", "Nossa Senhora da Glória", 
    "Nossa Senhora das Dores", "Nossa Senhora de Lourdes", "Nossa Senhora do Socorro", "Pacatuba", 
    "Pedra Mole", "Pedrinhas", "Pinhão", "Pirambu", "Poço Redondo", "Poço Verde", "Porto da Folha", 
    "Propriá", "Riachão do Dantas", "Riachuelo", "Ribeirópolis", "Rosário do Catete", "Salgado", 
    "Santa Luzia do Itanhy", "Santa Rosa de Lima", "Santana do São Francisco", "Santo Amaro das Brotas", 
    "São Cristóvão", "São Domingos", "São Francisco", "São Miguel do Aleixo", "Simão Dias", 
    "Siriri", "Telha", "Tobias Barreto", "Tomar do Geru", "Umbaúba"
]

def popular_sistema():
    db = SessionLocal()
    # Adicione suas 502 categorias aqui
    categorias_cruas = [ "Açougueiro", "Adestrador de Cães", "Administrador de Condomínios", "Advogado(a) Cível", 
        "Advogado(a) Criminalista", "Advogado(a) Trabalhista", "Afiador de Ferramentas", "Agente de Viagens", 
        "Agrônomo", "Ajudante de Mudança", "Alinhamento e Balanceamento", "Aluguel de Brinquedos", 
        "Aluguel de Carros", "Aluguel de Equipamentos", "Aluguel de Roupas de Festa", "Amestrador de Aves", 
        "Analista de Dados", "Analista de RH", "Analista de Sistemas", "Analista de Suporte TI", 
        "Animador de Festas", "Antenista", "Aparelhos Auditivos (Manutenção)", "Apicultor", 
        "Aposentadoria (Consultoria)", "Arqueólogo(a)", "Arquiteto(a)", "Arrumação de Closet", 
        "Artesanato em Barro", "Artesão", "Articulação Política (Consultoria)", "Artista Plástico", 
        "Assoalho e Parquet (Restauração)", "Assistência Técnica de Adega", "Assistência Técnica de Celular", 
        "Assistência Técnica de Fogão", "Assistência Técnica de Geladeira", "Assistência Técnica de Notebook", 
        "Assistência Técnica de Projetor", "Assistência Técnica de TV", "Assistente Social", 
        "Assistente Virtual", "Astrólogo(a)", "Atendimento ao Cliente (Treinamento)", "Atleta Profissional", 
        "Auditor Fiscal", "Aulas de Artesanato", "Aulas de Automobilismo", "Aulas de Backup e Nuvem", 
        "Aulas de Bateria", "Aulas de Canto", "Aulas de Capoeira", "Aulas de Culinária", 
        "Aulas de Dança de Salão", "Aulas de Desenho", "Aulas de Direção (Habilitação)", "Aulas de Espanhol", 
        "Aulas de Excel", "Aulas de Fotografia", "Aulas de Francês", "Aulas de Guitarra", 
        "Aulas de Informática Melhor Idade", "Aulas de Inglês", "Aulas de Investimentos", "Aulas de Italiano", 
        "Aulas de Jiu-Jitsu", "Aulas de Lutas", "Aulas de Matemática", "Aulas de Meditação", 
        "Aulas de Música", "Aulas de Natação", "Aulas de Piano", "Aulas de Pintura", 
        "Aulas de Português", "Aulas de Redação", "Aulas de Reforço Escolar", "Aulas de Surf", 
        "Aulas de Teatro", "Aulas de Tênis", "Aulas de Violão", "Aulas de Xadrez", 
        "Aulas Particulares", "Automóveis (Compra e Venda)", "Babá", "Babá de Pets (Pet Sitter)", 
        "Backup de Dados", "Bancário (Consultoria)", "Banho e Tosa", "Barbeiro", 
        "Barman/Bartender", "Berranteiro", "Bibliotecário(a)", "Bicicletaria (Conserto)", 
        "Bioconstrução", "Biólogo(a)", "Biomedicina", "Blogueiro(a)", 
        "Bolo de Rolo Profissional", "Bombeiro Civil", "Bombeiro Hidráulico", "Bordadeira", 
        "Borracheiro", "Botox e Preenchimento", "Buffet de Casamento", "Buffet de Churrasco", 
        "Buffet de Crepe", "Buffet de Massas", "Buffet de Pizza", "Buffet de Salgados", 
        "Buffet Infantil", "Buffet Japonês", "Buffet Vegano", "Cabeleireiro(a)", 
        "Caça Vazamento", "Caçamba de Entulho", "Cafeicultura", "Caixa de Som (Reparo)", 
        "Calceteiro", "Calheiro", "Caligrafia para Convites", "Caminhão de Mudança", 
        "Caminhão Pipa", "Canalização de Gás", "Cantor(a) para Eventos", "Capacho Personalizado", 
        "Capelania", "Capitão de Embarcação", "Capoteiro", "Cardápio Digital (Criação)", 
        "Carpinteiro", "Carregador de Móveis", "Carreteiro", "Cartazista", 
        "Cartonagem", "Cavalariça", "Cerimonialista", "Cervejeiro Artesanal", 
        "Cestaria", "Cestas de Café da Manhã", "Chapeador", "Chaveiro", 
        "Churrasqueiro Profissional", "Clínica de Estética", "Clínica Geral", "Coach de Carreira", 
        "Coach de Emagrecimento", "Coach de Finanças", "Coach de Relacionamento", "Coach de Vida", 
        "Cobrança de Dívidas", "Colocação de Drywall", "Colocação de Papel de Parede", "Colorista de Cabelo", 
        "Comercialização de Grãos", "Comissário de Bordo", "Composição Musical", "Comprador Pessoal (Personal Shopper)", 
        "Comunicação Visual", "Confeiteiro(a)", "Configuração de Roteador", "Conserto de Ar Condicionado", 
        "Conserto de Bicicleta Elétrica", "Conserto de Brinquedos", "Conserto de Câmera Fotográfica", "Conserto de Esteira Ergométrica", 
        "Conserto de Fogão", "Conserto de Geladeira", "Conserto de Máquina de Lavar", 
        "Conserto de Microondas", "Conserto de Óculos", "Conserto de Piscina", "Conserto de Relógio", 
        "Consultor de Imagem", "Consultor de Marketing", "Consultor de Moda", "Consultor de TI", 
        "Consultor de Vendas", "Consultoria Ambiental", "Consultoria de RH", "Consultoria de Segurança", 
        "Consultoria de Viagens", "Consultoria Educacional", "Consultoria Empresarial", "Consultoria Jurídica", 
        "Contabilidade para MEI", "Contador(a)", "Controle de Pragas (Dedetização)", "Copeiro(a)", 
        "Copywriter", "Corretor de Imóveis", "Corretor de Seguros", "Costura de Ajustes", 
        "Cozinheiro(a) para Eventos", "Cozinheiro(a) Particular", "Criação de Apps", "Criação de Conteúdo", 
        "Criação de Logotipos", "Criação de Sites", "Crochê e Tricô", "Cuidador(a) de Animais", 
        "Cuidador(a) de Idosos", "Culinária Funcional", "Culinária Nordestina", "Curadoria de Arte", 
        "Cyber Security", "Data Scientist", "Decorador(a) de Ambientes", "Decorador(a) de Festas", 
        "Dedetizador", "Delivery de Alimentos", "Dentista", "Depiladora", 
        "Dermatologista", "Desentupidor de Esgoto", "Desentupidor de Pia", "Designer de Interiores", 
        "Designer de Joias", "Designer de Moda", "Designer de Sobrancelhas", "Designer Gráfico", 
        "Despachante Aduaneiro", "Despachante de Veículos", "Detetive Particular", "Desenvolvedor Android", 
        "Desenvolvedor Back-end", "Desenvolvedor Front-end", "Desenvolvedor Full Stack", "Desenvolvedor iOS", 
        "Diarista", "Digitador(a)", "Digital Influencer", "Direito de Família", 
        "Direito Imobiliário", "DJ para Festas", "Doceira", "Documentação de Imóveis", 
        "Doula", "Drone (Filmagem e Foto)", "E-commerce Specialist", "Economista", 
        "Edição de Fotos", "Editor(a) de Vídeo", "Eletricista Automotivo", "Eletricista Industrial", 
        "Eletricista Residencial", "Eletrotécnico", "Embalador(a)", "Empresário(a) Musical", 
        "Encanador 24h", "Encadernação Artesanal", "Enfermeiro(a) Particular", "Engenheiro(a) Civil", 
        "Engenheiro(a) de Alimentos", "Engenheiro(a) de Produção", "Engenheiro(a) de Segurança", "Engenheiro(a) Elétrico", 
        "Engenheiro(a) Mecânico", "Entregador de Gás", "Escritor(a) / Ghostwriter", "Escultor(a)", 
        "Esotérico", "Esteticista Facial", "Esteticista Corporal", "Estofador", 
        "Estoquista", "Estrutura Metálica", "Fabricação de Brindes", "Fabricação de Portas e Janelas", 
        "Faxina de Obra", "Faxina Residencial", "Faz-Tudo (Marido de Aluguel)", "Fisioterapeuta", 
        "Fisioterapeuta Desportivo", "Florista", "Fonoaudiólogo(a)", "Fotógrafo(a) de Casamento", 
        "Fotógrafo(a) de Eventos", "Fotógrafo(a) de Gestante", "Fotógrafo(a) de Moda", "Fotógrafo(a) de Parto", 
        "Fotógrafo(a) de Produtos", "Fotógrafo(a) Newborn", "Frete e Mudanças", "Funileiro", 
        "Garçom / Garçonete", "Gastronomia (Consultoria)", "Geólogo(a)", "Gerente de Projetos", 
        "Gesseiro", "Gestor de Tráfego Pago", "Gestor de Tráfego Orgânico", "Ginecologista", 
        "Gourmetização de Pratos", "Governanta", "Gravação de Locução", "Gravação de Podcast", 
        "Guarda-Costas", "Guia de Turismo", "Guitarrista", "Harmonização Facial", 
        "Higiene Ocupacional", "Higienização de Ar Condicionado", "Higienização de Estofados", "Hipnoterapeuta", 
        "Homeopatia", "Host / Hostess", "Hotelaria (Consultoria)", "Iluminação de Eventos", 
        "Ilustrador(a)", "Impermeabilização de Lajes", "Impermeabilização de Sofá", "Impressão 3D", 
        "Instalador de Câmeras", "Instalador de Cercas Elétricas", "Instalador de Cortinas", "Instalador de Energia Solar", 
        "Instalador de Papel de Parede", "Instalador de Redes de Proteção", "Instalador de Som Automotivo", "Instalador de Ventilador", 
        "Instrutor de Academia", "Instrutor de Yoga", "Instrumentador Cirúrgico", "Intérprete de Libras", 
        "Inventário de Imóveis", "Investigador Particular", "Jardineiro", "Jatista", 
        "Joalheiro", "Jornalista", "Juiz de Paz", "Lava Jato 24h", 
        "Lava Jato a Seco", "Lavagem de Carpetes", "Lavagem de Cortinas", "Lavagem de Fachadas", 
        "Lavagem de Sofá", "Lavagem de Tapetes", "Lavanderia", "Leitura de Tarot", 
        "Letreirista", "Limpeza de Caixa d'Água", "Limpeza de Calhas", "Limpeza de Coifas", 
        "Limpeza de Fossa", "Limpeza de Piscina", "Limpeza de Terrenos", "Limpeza Pós-Obra", 
        "Linotipista", "Locação de Mesas e Cadeiras", "Locutor(a)", "Luthier", 
        "Maître", "Manicure e Pedicure", "Manutenção de Aquário", "Manutenção de Elevador", 
        "Manutenção de Gerador", "Manutenção Industrial", "Maquiador(a)", "Maquiagem Artística", 
        "Marceneiro", "Marido de Aluguel", "Marketing Político", "Marmorista", 
        "Massagista", "Massoterapeuta", "Mastologista", "Mecânico de Autos", 
        "Mecânico de Bicicletas", "Mecânico de Caminhão", "Mecânico de Máquina Industrial", "Mecânico de Motos", 
        "Medicina do Trabalho", "Mestre de Cerimônias", "Mestre de Obras", "Microagulhamento", 
        "Micropigmentação", "Modelagem de Roupas", "Modelista", "Monitor de Acampamento", 
        "Monitor de Recreação", "Montador de Estruturas", "Montador de Móveis", "Montagem de Computadores", 
        "Motoboy", "Motorista de Aplicativo", "Motorista de Caminhão", "Motorista de Van", 
        "Motorista Particular", "Musicoterapeuta", "Nutricionista", "Nutricionista Esportivo", 
        "Nutricionista Infantil", "Nutrólogo(a)", "Obstetra", "Office Boy", 
        "Oftalmologista", "Operador de Caixa", "Operador de Drone", "Operador de Empilhadeira", 
        "Operador de Máquinas Agrícolas", "Organizador de Casamentos", "Organizador de Eventos", "Organizador de Mudanças", 
        "Orientador Educacional", "Ortodontista", "Ortopedista", "Ourives", 
        "Padeiro(a) Artesanal", "Paisagista", "Palestrante", "Panfleteiro", 
        "Passadeira", "Pastelaria", "Patrolamento", "Pecuarista", 
        "Pedreiro de Acabamento", "Pedreiro de Alvenaria", "Pedreiro de Telhado", "Pedreiro Profissional", 
        "Pediatra", "Pedicuro", "Pequenos Reparos", "Perfuração de Poço", 
        "Personal Organizer", "Personal Shopper", "Personal Stylist", "Personal Trainer", 
        "Pet Sitter", "Pintor Automotivo", "Pintor de Paredes", "Pintor Decorativo", 
        "Pintura Artística", "Pintura de Portão", "Piscineiro", "Pizzaiolo(a)", 
        "Planejamento de Carreira", "Planejamento Financeiro", "Podólogo(a)", "Polimento Automotivo", 
        "Porteiro", "Prato Pronto (Marmita)", "Produção de Eventos", "Produção Musical", 
        "Professor(a) de Artes", "Professor(a) de Biologia", "Professor(a) de Dança", "Professor(a) de Educação Física", 
        "Professor(a) de Física", "Professor(a) de História", "Professor(a) de Inglês", "Professor(a) de Música", 
        "Professor(a) de Português", "Professor(a) de Química", "Professor(a) Particular", "Programador(a)", 
        "Projetista de Móveis", "Promotor(a) de Vendas", "Psicólogo(a)", "Psicólogo(a) Infantil", 
        "Psicopedagogo(a)", "Publicidade e Propaganda", "Puericultura", "Quadrinhista", 
        "Quiropraxia", "Radiologista", "Recreador Infantil", "Redator(a)", 
        "Redes de Proteção", "Redes Sociais (Gestão)", "Reforma de Estofados", "Reformas em Geral", 
        "Refrigerista", "Relojoeiro", "Reparo de Instrumentos", "Repórter", 
        "Representante Comercial", "Restaurador de Antiguidades", "Restaurador de Livros", "Revestimento de Parede", 
        "Revisão de Texto", "Roteirista", "Salgadeiro(a)", "Salão de Beleza", 
        "Sanfoneiro", "Sapateiro", "Secretária", "Segurança de Eventos", 
        "Segurança Patrimonial", "Segurança Privada", "Serralheiro", "Serviços de Delivery", 
        "Serviços de Jardinagem", "Serviços de Limpeza", "Serviços Gerais", "Social Media", 
        "Social Media Premium", "Software Engineer", "Soldador", "Sonoplasta", 
        "Suporte Técnico Remoto", "Suporte TI", "Tatuador(a)", "Taxista", 
        "Tecladista", "Técnico de Ar Condicionado", "Técnico de Celular", "Técnico de Computadores", 
        "Técnico de Som", "Técnico em Edificações", "Técnico em Eletrônica", "Técnico em Enfermagem", 
        "Técnico em Informática", "Técnico em Nutrição", "Técnico em Radiologia", "Técnico em Redes", 
        "Técnico em Refrigeração", "Técnico em Segurança do Trabalho", "Tecnologia da Informação", "Telemarketing", 
        "Terapeuta", "Terapeuta de Casal", "Terapeuta Holístico", "Terapeuta Ocupacional", 
        "Topógrafo", "Tradutor(a)", "Tráfego Pago", "Trancista", 
        "Transporte de Cargas", "Transporte de Passageiros", "Transporte Escola", "Transporte Executivo", 
        "Transporte Universitário", "Tricoteiro(a)", "Turismólogo(a)", "Urologista", 
        "Vendedor(a)", "Vendedor(a) de Loja", "Vendedor(a) Externo", "Veterinário", 
        "Veterinário de Grandes Portes", "Veterinário de Pets Exóticos", "Videomaker", "Vidraceiro", 
        "Vidraceiro Temperado", "Vigilante", "Violoncelista", "Violonista", 
        "Vocalista", "Voz e Violão", "Web Designer", "Web Developer", 
        "Wine Consultant (Sommelier)", "Yoga", "Zelador", "Zootecnista", 
        "Outros"] 
    
    lista_final = sorted(list(set(categorias_cruas)))
    if "Outros" in lista_final: lista_final.remove("Outros")
    lista_final.append("Outros")

    print("🚀 Sincronizando Banco de Dados... 🌵")
    for nome in lista_final:
        if not db.query(Categoria).filter_by(nome=nome).first():
            db.add(Categoria(nome=nome))
    db.commit()
    db.close()
    print("✅ Banco pronto!")

if __name__ == "__main__":
    popular_sistema()